name: prueba

on:
    push:
        branches:
            - main

jobs:
    Prueba-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: mi primer action
              run: echo 'hola mundo'

 
